site_name: Plant Genomics Training
site_description: Training for plant genomics
site_author: Anna Syme
#site_favicon: favicon.ico

site_url: 'https://plant-genomics.github.io/training/'

repo_name: 'plant-genomics/training'
repo_url: 'https://github.com/plant-genomics/training'

copyright: '&copy; The authors; 2019-'

#theme: yeti
theme: cluster

extra:
    feature:
        tabs: true
    social:
        - type: 'github'
          link: 'https://github.com/plant-genomics/training'

markdown_extensions:
    - admonition
    - smarty
    - tables
    - markdown_include.include
    - codehilite
    - pymdownx.details
    - footnotes


pages:
- Welcome: index.md
- Tools: modules/tools.md
- Compute: modules/compute.md
- Links: modules/training-links.md
- Data: modules/sample-data.md
- Galaxy: modules/galaxy.md

# - About: about/index.md
