site_name: Plant Genomics Training
site_description: Training for plant genomics
site_author: Anna Syme
#site_favicon: favicon.ico

site_url: 'https://plant-genomics.github.io/training/'

#repo_name: 'plant-genomics/training'
#repo_url: 'https://github.com/plant-genomics/training'

copyright: '&copy; The authors; 2019-'

#theme: yeti
#theme: cluster
theme: windmill


nav:
  - Home: index.md
  - Getting started: modules/start.md
  - Tools: modules/tools.md
  - Data: modules/data.md
  - Virtual environments: modules/vms.md
  - Using containers:  modules/docker.md
  - Using HPC: modules/hpc.md
  - Platforms: modules/platforms.md
  - Help: modules/help.md


extra:
    article_nav_top: false
    article_nav_bottom: false
    logo: leaf2.svg


    feature:
        tabs: true
    social:
        type: 'github'
        link: 'https://github.com/plant-genomics/training'
        fa_logo: 'pagelines'

markdown_extensions:
    - admonition
    - smarty
    - tables
    - markdown_include.include
    - codehilite
    - pymdownx.details
    - footnotes
extra_css:
    - css/style.css





# - About: about/index.md
