site_name: Plant Genomics Training
site_description: Training for plant genomics
site_author: Anna Syme
#site_favicon: favicon.ico

site_url: 'https://plant-genomics.github.io/training/'

#repo_name: 'plant-genomics/training'
#repo_url: 'https://github.com/plant-genomics/training'

copyright: '&copy; The authors; 2019-'

#theme: yeti
#theme: cluster
theme: windmill


nav:
  - Home: index.md
  - Tutorials: modules/tutorials.md
  - Galaxy: modules/galaxy.md
  - Genome assembly: modules/assembly.md
  - Phylogenomics: modules/phylogenomics.md
  - Variant calling: modules/variants.md
  - RNA-seq: modules/rna.md
  - Data: modules/data.md
  - Databases: modules/databases.md


  - Links: modules/orgs.md
  - Help: modules/help.md







  #need to check these: may be incorrect:
  #- Virtual environments: modules/envs.md
  #- Using containers:  modules/docker.md
  #- Using HPC: modules/hpc.md
  #- Workflows: modules/nextflow.md



extra:
    article_nav_top: false
    article_nav_bottom: false
    logo: leaf2.svg


    feature:
        tabs: true
    social:
        type: 'github'
        link: 'https://github.com/plant-genomics/training'
        fa_logo: 'pagelines'

markdown_extensions:
    - admonition
    - smarty
    - tables
    - markdown_include.include
    - codehilite
    - pymdownx.details
    - footnotes
extra_css:
    - css/style.css





# - About: about/index.md
